# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the Gradle Daemon.
# Setting a larger heap size helps avoid OutOfMemoryError during build.
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects.
org.gradle.parallel=true

# Enables the use of AndroidX libraries.
android.useAndroidX=true

# Automatically convert third-party libraries to use AndroidX.
android.enableJetifier=true

# Increase the number of worker processes.
org.gradle.workers.max=4
